// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ulid.proto
// Protobuf Java Version: 4.31.1

package com.workflow.ulid.grpc;

@com.google.protobuf.Generated
public interface BatchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ulid.BatchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Client identifier
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Client identifier
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * Number of ULIDs to reserve
   * </pre>
   *
   * <code>int32 batch_size = 2;</code>
   * @return The batchSize.
   */
  int getBatchSize();
}
