// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ulid.proto
// Protobuf Java Version: 4.31.1

package com.workflow.ulid.grpc;

@com.google.protobuf.Generated
public interface BatchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ulid.BatchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Client node ID assigned by the server (0-1023)
   * </pre>
   *
   * <code>int32 node_id = 1;</code>
   * @return The nodeId.
   */
  int getNodeId();

  /**
   * <pre>
   * Reserved timestamp range start (in milliseconds)
   * </pre>
   *
   * <code>int64 timestamp_start = 2;</code>
   * @return The timestampStart.
   */
  long getTimestampStart();

  /**
   * <pre>
   * Reserved timestamp range end (in milliseconds)
   * </pre>
   *
   * <code>int64 timestamp_end = 3;</code>
   * @return The timestampEnd.
   */
  long getTimestampEnd();

  /**
   * <pre>
   * Time to wait before requesting another batch (in milliseconds)
   * </pre>
   *
   * <code>int64 wait_time_ms = 4;</code>
   * @return The waitTimeMs.
   */
  long getWaitTimeMs();
}
