// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ulid.proto
// Protobuf Java Version: 4.31.1

package com.workflow.ulid.grpc;

@com.google.protobuf.Generated
public interface UlidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ulid.UlidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional client identifier (can be used for logging or rate limiting)
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Optional client identifier (can be used for logging or rate limiting)
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
