// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ulid.proto
// Protobuf Java Version: 4.31.1

package com.workflow.ulid.grpc;

@com.google.protobuf.Generated
public interface UlidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ulid.UlidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The generated ULID
   * </pre>
   *
   * <code>string ulid = 1;</code>
   * @return The ulid.
   */
  java.lang.String getUlid();
  /**
   * <pre>
   * The generated ULID
   * </pre>
   *
   * <code>string ulid = 1;</code>
   * @return The bytes for ulid.
   */
  com.google.protobuf.ByteString
      getUlidBytes();

  /**
   * <pre>
   * Timestamp of when the ULID was generated
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
