// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ulid.proto
// Protobuf Java Version: 4.31.1

package com.workflow.ulid.grpc;

@com.google.protobuf.Generated
public final class UlidServiceProto {
  private UlidServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      UlidServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ulid_UlidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ulid_UlidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ulid_UlidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ulid_UlidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ulid_BatchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ulid_BatchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ulid_BatchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ulid_BatchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nulid.proto\022\004ulid\" \n\013UlidRequest\022\021\n\tcli" +
      "ent_id\030\001 \001(\t\"/\n\014UlidResponse\022\014\n\004ulid\030\001 \001" +
      "(\t\022\021\n\ttimestamp\030\002 \001(\003\"5\n\014BatchRequest\022\021\n" +
      "\tclient_id\030\001 \001(\t\022\022\n\nbatch_size\030\002 \001(\005\"f\n\r" +
      "BatchResponse\022\017\n\007node_id\030\001 \001(\005\022\027\n\017timest" +
      "amp_start\030\002 \001(\003\022\025\n\rtimestamp_end\030\003 \001(\003\022\024" +
      "\n\014wait_time_ms\030\004 \001(\0032\303\001\n\013UlidService\0227\n\014" +
      "GenerateUlid\022\021.ulid.UlidRequest\032\022.ulid.U" +
      "lidResponse\"\000\022@\n\025GenerateMonotonicUlid\022\021" +
      ".ulid.UlidRequest\032\022.ulid.UlidResponse\"\000\022" +
      "9\n\014ReserveBatch\022\022.ulid.BatchRequest\032\023.ul" +
      "id.BatchResponse\"\000B,\n\026com.workflow.ulid." +
      "grpcB\020UlidServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ulid_UlidRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ulid_UlidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ulid_UlidRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_ulid_UlidResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ulid_UlidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ulid_UlidResponse_descriptor,
        new java.lang.String[] { "Ulid", "Timestamp", });
    internal_static_ulid_BatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ulid_BatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ulid_BatchRequest_descriptor,
        new java.lang.String[] { "ClientId", "BatchSize", });
    internal_static_ulid_BatchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ulid_BatchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ulid_BatchResponse_descriptor,
        new java.lang.String[] { "NodeId", "TimestampStart", "TimestampEnd", "WaitTimeMs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
