// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ulid.proto
// Protobuf Java Version: 4.31.1

package com.workflow.ulid.grpc;

/**
 * <pre>
 * Response containing a generated ULID
 * </pre>
 *
 * Protobuf type {@code ulid.UlidResponse}
 */
@com.google.protobuf.Generated
public final class UlidResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ulid.UlidResponse)
    UlidResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      UlidResponse.class.getName());
  }
  // Use UlidResponse.newBuilder() to construct.
  private UlidResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UlidResponse() {
    ulid_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.workflow.ulid.grpc.UlidServiceProto.internal_static_ulid_UlidResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.workflow.ulid.grpc.UlidServiceProto.internal_static_ulid_UlidResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.workflow.ulid.grpc.UlidResponse.class, com.workflow.ulid.grpc.UlidResponse.Builder.class);
  }

  public static final int ULID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ulid_ = "";
  /**
   * <pre>
   * The generated ULID
   * </pre>
   *
   * <code>string ulid = 1;</code>
   * @return The ulid.
   */
  @java.lang.Override
  public java.lang.String getUlid() {
    java.lang.Object ref = ulid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ulid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The generated ULID
   * </pre>
   *
   * <code>string ulid = 1;</code>
   * @return The bytes for ulid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUlidBytes() {
    java.lang.Object ref = ulid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ulid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * Timestamp of when the ULID was generated
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ulid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ulid_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ulid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ulid_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.workflow.ulid.grpc.UlidResponse)) {
      return super.equals(obj);
    }
    com.workflow.ulid.grpc.UlidResponse other = (com.workflow.ulid.grpc.UlidResponse) obj;

    if (!getUlid()
        .equals(other.getUlid())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ULID_FIELD_NUMBER;
    hash = (53 * hash) + getUlid().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.workflow.ulid.grpc.UlidResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.workflow.ulid.grpc.UlidResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.workflow.ulid.grpc.UlidResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.workflow.ulid.grpc.UlidResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response containing a generated ULID
   * </pre>
   *
   * Protobuf type {@code ulid.UlidResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ulid.UlidResponse)
      com.workflow.ulid.grpc.UlidResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.workflow.ulid.grpc.UlidServiceProto.internal_static_ulid_UlidResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.workflow.ulid.grpc.UlidServiceProto.internal_static_ulid_UlidResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.workflow.ulid.grpc.UlidResponse.class, com.workflow.ulid.grpc.UlidResponse.Builder.class);
    }

    // Construct using com.workflow.ulid.grpc.UlidResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ulid_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.workflow.ulid.grpc.UlidServiceProto.internal_static_ulid_UlidResponse_descriptor;
    }

    @java.lang.Override
    public com.workflow.ulid.grpc.UlidResponse getDefaultInstanceForType() {
      return com.workflow.ulid.grpc.UlidResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.workflow.ulid.grpc.UlidResponse build() {
      com.workflow.ulid.grpc.UlidResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.workflow.ulid.grpc.UlidResponse buildPartial() {
      com.workflow.ulid.grpc.UlidResponse result = new com.workflow.ulid.grpc.UlidResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.workflow.ulid.grpc.UlidResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ulid_ = ulid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.workflow.ulid.grpc.UlidResponse) {
        return mergeFrom((com.workflow.ulid.grpc.UlidResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.workflow.ulid.grpc.UlidResponse other) {
      if (other == com.workflow.ulid.grpc.UlidResponse.getDefaultInstance()) return this;
      if (!other.getUlid().isEmpty()) {
        ulid_ = other.ulid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ulid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ulid_ = "";
    /**
     * <pre>
     * The generated ULID
     * </pre>
     *
     * <code>string ulid = 1;</code>
     * @return The ulid.
     */
    public java.lang.String getUlid() {
      java.lang.Object ref = ulid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ulid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The generated ULID
     * </pre>
     *
     * <code>string ulid = 1;</code>
     * @return The bytes for ulid.
     */
    public com.google.protobuf.ByteString
        getUlidBytes() {
      java.lang.Object ref = ulid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ulid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The generated ULID
     * </pre>
     *
     * <code>string ulid = 1;</code>
     * @param value The ulid to set.
     * @return This builder for chaining.
     */
    public Builder setUlid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ulid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The generated ULID
     * </pre>
     *
     * <code>string ulid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUlid() {
      ulid_ = getDefaultInstance().getUlid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The generated ULID
     * </pre>
     *
     * <code>string ulid = 1;</code>
     * @param value The bytes for ulid to set.
     * @return This builder for chaining.
     */
    public Builder setUlidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ulid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Timestamp of when the ULID was generated
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Timestamp of when the ULID was generated
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of when the ULID was generated
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ulid.UlidResponse)
  }

  // @@protoc_insertion_point(class_scope:ulid.UlidResponse)
  private static final com.workflow.ulid.grpc.UlidResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.workflow.ulid.grpc.UlidResponse();
  }

  public static com.workflow.ulid.grpc.UlidResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UlidResponse>
      PARSER = new com.google.protobuf.AbstractParser<UlidResponse>() {
    @java.lang.Override
    public UlidResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UlidResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UlidResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.workflow.ulid.grpc.UlidResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

